services:
  django:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/plagigram
    command: >
      bash -c "python plagigram/insta/wait_db.py &&
               python plagigram/manage.py makemigrations &&
               python plagigram/manage.py migrate &&
               gunicorn plagigram.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
       - pgdb

  pgdb:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

volumes:
  my_db:

