services:
  django:
    build: ./app
    env_file:
      - .env.prod
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn plagigram.wsgi:application --bind 0.0.0.0:8000"

    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
       - pgdb
    networks:
      - task-12-create-basic-application_default

  pgdb:
    image: postgres:latest
    env_file:
      - .env.prod.db
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data
    networks:
      - task-12-create-basic-application_default

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - task-12-create-basic-application_default

networks:
  task-12-create-basic-application_default:
    driver: bridge

volumes:
  my_db:
  static_volume:
  media_volume:

